# Nome do Workflow: Visível na aba "Actions" do GitHub
name: Primeiro Workflow

# Gatilho (Trigger): Define quando o workflow será executado.
on:
  # Executa em todo push para a branch 'main'
  push:
    branches: [ "main" ]
  
  # Permite que o workflow seja executado manualmente a partir da interface do GitHub
  workflow_dispatch:

# Jobs: Um workflow é composto por um ou mais jobs, que rodam em paralelo por padrão.
jobs:
  # Nome do nosso primeiro job
  primeiro-job:
    # Runner: Define a máquina virtual onde o job será executado. 'ubuntu-latest' é uma boa escolha padrão.
    runs-on: ubuntu-latest

    # Steps: Uma sequência de tarefas que serão executadas no job.
    steps:
      - name: Boas-vindas
        run: echo "Yaldabaoth"
      - name: Mostra o diretório de trabalho
        run: pwd
      - name: Lista os arquivos no diretório home
        run: ls ~ -a